# Generated by Django 3.2.4 on 2021-10-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0066_stockitem_scheduled_for_deletion'),
        ('part', '0073_auto_20211013_1048'),
        ('ShopifyIntegrationPlugin', '0003_shopifywebhook_shopify_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylevel',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShopifyInventoryLevel', to='stock.stockitem', verbose_name='StockItem'),
        ),
        migrations.AddField(
            model_name='variant',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShopifyVariant', to='part.part', verbose_name='Part'),
        ),
    ]
