# Generated by Django 3.2.4 on 2021-10-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('body_html', models.CharField(max_length=250, verbose_name='Body HTML')),
                ('vendor', models.CharField(max_length=250, verbose_name='Vendor')),
                ('product_type', models.CharField(max_length=250, verbose_name='Product Type')),
                ('handle', models.CharField(max_length=250, verbose_name='Handle')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('sku', models.CharField(max_length=250, verbose_name='SKU')),
                ('barcode', models.CharField(max_length=250, verbose_name='Barcode')),
                ('price', models.CharField(max_length=250, verbose_name='Price')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('inventory_item_id', models.IntegerField(verbose_name='Inventory item ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ShopifyIntegrationPlugin.product', verbose_name='Product')),
            ],
        ),
    ]
