# Generated by Django 3.2.4 on 2021-10-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyIntegrationPlugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(verbose_name='Available')),
                ('location_id', models.IntegerField(verbose_name='Location ID')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='ShopifyIntegrationPlugin.variant', verbose_name='Variant')),
            ],
        ),
    ]
