# Generated by Django 3.2.4 on 2021-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyIntegrationPlugin', '0002_inventorylevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='id',
        ),
        migrations.AlterField(
            model_name='variant',
            name='inventory_item_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Inventory item ID'),
        ),
    ]
